### ISSUE TITLE
Vertical borders in table headers look visually unpleasing in Firefox

### ISSUE THREAD

**Issue by rohieb** [rtfd/sphinx_rtd_theme#581]
### Problem

Vertical borders in table headers look visually unpleasing when viewed with Firefox, and disturb the reader by attracting attention to them. Screenshot of the current behaviour:

![54e3f9e6-17e0-11e8-a873-6f5da530dbd1](https://user-images.githubusercontent.com/192014/36545951-65cd9b7c-17ea-11e8-9ba8-c329714ded58.png)

### Reproducible Project

Any example that produces tables with headers, for example in <https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/lists_tables.html>

#### Expected Results

Vertical borders in table headers look visually more pleasing and don't disturb the reader. This could be reached by coloring them the same as all the other table cell borders, for example, by adding a simple CSS rule:

``` css
.rst-content table.docutils thead th, .rst-content table.field-list thead th {
    border-color: #e1e4e5;
}
```

I was not able to find out what the respective change on the SASS side was.

Screenshot:
![a2e263bc-17e0-11e8-aaab-ab3c26dc6131](https://user-images.githubusercontent.com/192014/36545950-6595af14-17ea-11e8-9b4f-44fbfb59d73f.png)

### Environment Info

- RTD Theme Version: latest

**Comment by tuukkamustonen** [comment]
I've seen this also, but looks like it's already fixed in the latest build? Cannot see the problem at https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/lists_tables.html anymore?

**Comment by rohieb** [comment]
I can still see it in the section https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/lists_tables.html#grid-tables

**Comment by tuukkamustonen** [comment]
Checked again: you're right, it's like that on **Firefox**, but fixed on Chrome/Opera (Webkit).

**Comment by rohieb** [comment]
Oh right, I can confirm this!

**Comment by rohieb** [comment]
Thanks a lot, @jessetan!
